### ISSUE TITLE
how to install this ?

### ISSUE THREAD

**Issue by zqc0512** [huangll99/zabbix-monitor#1]
how to install this ?

**Comment by huangll99** [comment]
just a django project.

**Comment by jinjin123** [comment]
he mean is  how to deploy this project :) @huangll99

**Comment by klauswang0116** [comment]
how to install this ?

**Comment by jinjin123** [comment]
@klauswang0116  django  1.11  resetframework reset-swoogxxx ,I dont know the full name , u can try to  startup manage  u will see what model lose  and go to install the package, so easily
