### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by haisheng666** [huangll99/zabbix-monitor#4]
你这个文件/monitor-py/monitor/api中的rest_framework.py这个脚本在哪里，你忘记上传了把？

**Comment by huangll99** [comment]
用pip install rest_framework装一下

**Comment by huangll99** [comment]
> 你这个文件/monitor-py/monitor/api中的rest_framework.py这个脚本在哪里，你忘记上传了把？

用pip install rest_framework装一下

**Comment by haisheng666** [comment]
好吧!我下来试一试,谢谢了!



821058392@qq.com
 
From: 黄林林
Date: 2018-12-06 14:53
To: huangll99/zabbix-monitor
CC: haisheng666; Author
Subject: Re: [huangll99/zabbix-monitor] issue (#4)
用pip install rest_framework装一下
